-- Migration: create car_auctions table
-- Applied to: bpdafetvjyvvwbksvowu (starwms shared project)
-- Date: 2026-05-19
-- Note: This file is a record of the migration already applied via Supabase MCP.
--       Do NOT run again.

create table if not exists public.car_auctions (
  id bigint generated by default as identity primary key,
  -- Source columns (verbatim from Excel '이번주거래(누적)')
  auction_date date not null,                -- 경매일자
  vehicle_class text,                        -- 차종 (RV/세단/SUV)
  maker text,                                -- 제작사
  car_name text not null,                    -- 차명 (e.g. K5)
  model_name text not null,                  -- 모델명 (e.g. K5 3세대(19년~현재)
  full_title text,                           -- 차종(*) full descriptive title
  year int,                                  -- 년식
  first_registered date,                     -- 최초등록일
  transmission text,                         -- 변속기
  engine_code text,                          -- 엔진형식코드
  engine_cc int,                             -- 배기량
  fuel text,                                 -- 연료
  grade text,                                -- 등급 (2글자, e.g. "BC")
  color text,                                -- 색상
  mileage_km int,                            -- 주행거리 (km)
  search_category text,                      -- 검색구 (국산/수입)
  options text,                              -- 옵션 (comma-separated string)
  product_type text,                         -- 상품구분
  accident_count int,                        -- 사고품횟수
  inspection_notes text,                     -- 검사내용
  start_price int,                           -- 시작가 (만원)
  bid_price int,                             -- 응찰가 (만원)
  final_price int,                           -- 낙찰금액VAT포함 (만원)
  status text not null,                      -- 낙찰/유찰
  -- Computed at ingest time
  grade_first char(1),                       -- 등급 첫 글자 (A/B/C/D)
  is_outlier boolean default false,          -- mileage_km < 100 OR > 500,000
  row_hash text unique,                      -- sha256 dedup key (see ingest script)
  ingested_at timestamptz default now()
);

-- Primary lookup index: car_name + model_name + status + auction_date (DESC for recency)
create index if not exists idx_car_auctions_lookup
  on public.car_auctions (car_name, model_name, status, auction_date desc);

create index if not exists idx_car_auctions_year
  on public.car_auctions (year);

create index if not exists idx_car_auctions_grade_first
  on public.car_auctions (grade_first);

-- RLS: deny all for anon; app uses service-role key which bypasses RLS.
alter table public.car_auctions enable row level security;
-- No policies = deny all for non-service-role roles.
